In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,precision_score,recall_score

In [2]:
data=pd.read_csv("https://bit.ly/2RBzgqH")

In [3]:
data

age          workclass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gains  capital-loss  hours-per-week  native-country  \
0         Male           2174             0              40   United-States   
1         Male              0             0              13   United-States   
2         Male              0             0              40   United-States   
3         Male              0             0              40   United-States   
4       Female              0             0              40            Cuba   
...        ...            ...           ...             ...             ...   
32556   Female              0             0              38   United-States   
32557     Male              0             0              40   United-States   
32558   Female              0             0              40   United-States   
32559     Male              0             0              20   United-States   
32560   Female          15024             0              40   United-States   

       target  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [4]:
data.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gains        0
capital-loss         0
hours-per-week       0
native-country     583
target               0
dtype: int64

In [5]:
data=data.fillna(method="ffill")

In [6]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gains     0
capital-loss      0
hours-per-week    0
native-country    0
target            0
dtype: int64

In [7]:
data2=data[['age','workclass','education-num','marital-status','occupation','capital-gains','capital-loss','hours-per-week','native-country']]

In [8]:
data2

age          workclass  education-num       marital-status  \
0       39          State-gov             13        Never-married   
1       50   Self-emp-not-inc             13   Married-civ-spouse   
2       38            Private              9             Divorced   
3       53            Private              7   Married-civ-spouse   
4       28            Private             13   Married-civ-spouse   
...    ...                ...            ...                  ...   
32556   27            Private             12   Married-civ-spouse   
32557   40            Private              9   Married-civ-spouse   
32558   58            Private              9              Widowed   
32559   22            Private              9        Never-married   
32560   52       Self-emp-inc              9   Married-civ-spouse   

               occupation  capital-gains  capital-loss  hours-per-week  \
0            Adm-clerical           2174             0              40   
1         Exec-managerial              0             0              13   
2       Handlers-cleaners              0             0              40   
3       Handlers-cleaners              0             0              40   
4          Prof-specialty              0             0              40   
...                   ...            ...           ...             ...   
32556        Tech-support              0             0              38   
32557   Machine-op-inspct              0             0              40   
32558        Adm-clerical              0             0              40   
32559        Adm-clerical              0             0              20   
32560     Exec-managerial          15024             0              40   

       native-country  
0       United-States  
1       United-States  
2       United-States  
3       United-States  
4                Cuba  
...               ...  
32556   United-States  
32557   United-States  
32558   United-States  
32559   United-States  
32560   United-States  

[32561 rows x 9 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
pre=LabelEncoder()

In [10]:
data2['workclass']=pre.fit_transform(data2['workclass'].astype('str'))
data2['marital-status']=pre.fit_transform(data2['marital-status'].astype('str'))
data2['occupation']=pre.fit_transform(data2['occupation'].astype('str'))
data2['native-country']=pre.fit_transform(data2['native-country'].astype('str'))
data['target']=pre.fit_transform(data['target'].astype('str'))

C:\Users\saipr\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\saipr\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\saipr\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in

In [11]:
X12=data2
Y12=data['target']

In [12]:
model12=GaussianNB()
model12=model12.fit(X12,Y12)

In [13]:
Y_predict=model12.predict([[39, 6, 13, 4, 0, 2174, 0, 40, 38]])

In [14]:
Y_predict

array([0])

In [15]:
from sklearn import tree
model123=tree.DecisionTreeClassifier()
model123=model123.fit(X12,Y12)

In [16]:
Y_predict=model123.predict([[39, 6, 13, 4, 0, 2174, 0, 40, 38]])


In [17]:
Y_predict

array([0])

In [18]:
from sklearn.svm import SVC

In [19]:
MODEL=SVC()
MODEL=MODEL.fit(X12,Y12)

In [20]:
Y_predict=MODEL.predict([[39, 6, 13, 4, 0, 2174, 0, 40, 38]])

In [21]:
Y_predict

array([0])

In [22]:
X_train,X_test,Y_train,Y_test=train_test_split(X12,Y12,test_size=0.1,random_state=101)


In [23]:
dev=X_test.shape[0]/X_train.shape[0]

In [24]:
X_train,X_dev,Y_train,Y_dev=train_test_split(X_train,Y_train,test_size=dev,random_state=101)

In [25]:
print(X_train.shape,X_dev.shape,X_test.shape,Y_train.shape,Y_dev.shape,Y_test.shape)

(26047, 9) (3257, 9) (3257, 9) (26047,) (3257,) (3257,)


In [26]:
model_NB=GaussianNB()
model_NB=model_NB.fit(X_train,Y_train)

In [27]:
model_dc=tree.DecisionTreeClassifier()
model_dc=model_dc.fit(X_train,Y_train)

In [28]:
model_SVM=SVC()
model_SVM=model_SVM.fit(X_train,Y_train)

In [29]:
sets={"naive":{"accuracy":[],"precision":[],"recall":[]},
      "DTC":{"accuracy":[],"precision":[],"recall":[]},
      "SVM":{"accuracy":[],"precision":[],"recall":[]}}

In [30]:
X_sets=[X_train,X_dev,X_test]
Y_sets=[Y_train,Y_dev,Y_test]

In [31]:
for i in range(0,len(X_sets)):
    Y_pred_NB=model_NB.predict(X_sets[i])
    sets["naive"]["accuracy"].append(accuracy_score(Y_sets[i],Y_pred_NB))
    sets["naive"]["precision"].append(precision_score(Y_sets[i],Y_pred_NB))
    sets["naive"]["recall"].append(recall_score(Y_sets[i],Y_pred_NB))
    Y_pred_dc=model_dc.predict(X_sets[i])
    sets["DTC"]["accuracy"].append(accuracy_score(Y_sets[i],Y_pred_dc))
    sets["DTC"]["precision"].append(precision_score(Y_sets[i],Y_pred_dc))
    sets["DTC"]["recall"].append(recall_score(Y_sets[i],Y_pred_dc))
    Y_pred_SVM=model_SVM.predict(X_sets[i])
    sets["SVM"]["accuracy"].append(accuracy_score(Y_sets[i],Y_pred_SVM))
    sets["SVM"]["precision"].append(precision_score(Y_sets[i],Y_pred_SVM))
    sets["SVM"]["recall"].append(recall_score(Y_sets[i],Y_pred_SVM))
    

In [32]:
sets

{'naive': {'accuracy': [0.7966368487733713,
   0.7909118821000921,
   0.8068774946269573],
  'precision': [0.6658727458319156, 0.6834733893557423, 0.6777777777777778],
  'recall': [0.3120216836734694, 0.30049261083743845, 0.32232496697490093]},
 'DTC': {'accuracy': [0.9716666026797712,
   0.803193122505373,
   0.8182376420018422],
  'precision': [0.9800485773768216, 0.6114732724902217, 0.6086956521739131],
  'recall': [0.9006696428571429, 0.5775862068965517, 0.6103038309114928]},
 'SVM': {'accuracy': [0.8024724536414942,
   0.7958243782622045,
   0.8099478047282775],
  'precision': [0.7411210954214805, 0.7474747474747475, 0.7429577464788732],
  'recall': [0.27614795918367346, 0.2733990147783251, 0.27873183619550856]}}

In [33]:
from sklearn.neural_network import MLPClassifier

In [56]:
MODEL1=MLPClassifier(random_state=101,max_iter=1000,hidden_layer_sizes=(150,150,150))

In [57]:
MODEL1=MODEL1.fit(X_train,Y_train)


In [58]:
sets1=["training",'validation','testing']

In [59]:
for i in range(0,len(sets1)):
    Y_pre=MODEL1.predict(X_sets[i])
    print(sets1[i],accuracy_score(Y_sets[i],Y_pre))

training 0.8377548278112642
validation 0.8206938900828984
testing 0.8375805956401596


In [61]:
pred = MODEL1.predict([[-0.33,0.67,1,1,0,0,0.8,-1,0.5]])
print(pred)

[0]
